package:
  name: mpl-probscale
  version: 0.2.4

source:
  path: ../

build:
  script: python setup.py install
  number: 0

requirements:
  build:
    - python
    - setuptools
    - numpy
    - matplotlib

  run:
    - python
    - numpy
    - matplotlib
    - pytest

test:
  imports:
    - probscale

  commands:
    - python -c "import sys; import matplotlib as mpl; mpl.use('agg'); import probscale as ps; sys.exit(ps.test('--mpl'))"

  requires:
    - mock  # [py27]
    - pytest
    - pytest-mpl
    - scipy

about:
  home: http://matplotlib.org/mpl-probscale/
  license:  BSD License
  summary: 'Probability scales for matplotlib.'
