# This workflow will upload a Python Package to PyPI when a release is created.
# For more information see: https://docs.astral.sh/uv/guides/publish/

name: Publish Python Package

on:
  release:
    types: [created]

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install uv
      uses: astral-sh/setup-uv@v6
    - name: Build
      run: uv build
    - name: Publish
      env:
        UV_PUBLISH_USERNAME: ${{ secrets.PMH_PYPI_USER }}
        UV_PUBLISH_PASSWORD: ${{ secrets.PMH_PYPI_PASS }}
      run: uv publish