name: ruff 'n' ty
on: [pull_request]

jobs:
    lint:
      runs-on: ubuntu-latest
      strategy:
        matrix:
          tool:
            - ruff
            - ty
      steps:
        - uses: actions/checkout@v7
        - name: Install uv
          uses: astral-sh/setup-uv@v7
        - name: Install dependencies
          run: uv sync --locked
        # Update output format to enable automatic inline annotations.
        - name: Run ${{ matrix.tool }}
          run: uv run ${{ matrix.tool }} check --output-format=github .
